-- Supabase setup for Fal-Breeze Sales Record
-- Run this whole file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'cashier' check (role in ('cashier','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  sale_date date not null default current_date,
  customer text not null,
  item text not null,
  qty integer not null check (qty > 0),
  amount numeric(12,2) not null check (amount >= 0),
  payment_method text not null check (payment_method in ('Cash','Card','Transfer')),
  status text not null default 'Paid' check (status in ('Paid','Pending','Cancelled')),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stock (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  qty numeric(12,2) not null default 0 check (qty >= 0),
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id uuid,
  action text not null check (action in ('INSERT','UPDATE','DELETE')),
  changed_by uuid references auth.users(id),
  old_data jsonb,
  new_data jsonb,
  changed_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sales_updated_at on public.sales;
create trigger sales_updated_at before update on public.sales
for each row execute function public.set_updated_at();

drop trigger if exists stock_updated_at on public.stock;
create trigger stock_updated_at before update on public.stock
for each row execute function public.set_updated_at();

create or replace function public.audit_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.audit_log(table_name, record_id, action, changed_by, new_data)
    values (tg_table_name, new.id, 'INSERT', auth.uid(), to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.audit_log(table_name, record_id, action, changed_by, old_data, new_data)
    values (tg_table_name, new.id, 'UPDATE', auth.uid(), to_jsonb(old), to_jsonb(new));
    return new;
  else
    insert into public.audit_log(table_name, record_id, action, changed_by, old_data)
    values (tg_table_name, old.id, 'DELETE', auth.uid(), to_jsonb(old));
    return old;
  end if;
end;
$$;

drop trigger if exists sales_audit on public.sales;
create trigger sales_audit after insert or update or delete on public.sales
for each row execute function public.audit_changes();

drop trigger if exists stock_audit on public.stock;
create trigger stock_audit after insert or update or delete on public.stock
for each row execute function public.audit_changes();

alter table public.profiles enable row level security;
alter table public.sales enable row level security;
alter table public.stock enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists "profiles_read_authenticated" on public.profiles;
create policy "profiles_read_authenticated" on public.profiles
for select to authenticated using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
for insert to authenticated with check (id = auth.uid());

drop policy if exists "sales_read_authenticated" on public.sales;
create policy "sales_read_authenticated" on public.sales
for select to authenticated using (true);

drop policy if exists "sales_insert_authenticated" on public.sales;
create policy "sales_insert_authenticated" on public.sales
for insert to authenticated with check (created_by = auth.uid());

drop policy if exists "sales_delete_admin" on public.sales;
create policy "sales_delete_admin" on public.sales
for delete to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

drop policy if exists "stock_read_authenticated" on public.stock;
create policy "stock_read_authenticated" on public.stock
for select to authenticated using (true);

drop policy if exists "stock_insert_authenticated" on public.stock;
create policy "stock_insert_authenticated" on public.stock
for insert to authenticated with check (created_by = auth.uid() and updated_by = auth.uid());

drop policy if exists "stock_update_authenticated" on public.stock;
create policy "stock_update_authenticated" on public.stock
for update to authenticated using (true) with check (true);

drop policy if exists "stock_delete_admin" on public.stock;
create policy "stock_delete_admin" on public.stock
for delete to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

drop policy if exists "audit_read_authenticated" on public.audit_log;
create policy "audit_read_authenticated" on public.audit_log
for select to authenticated using (true);

grant select on public.profiles, public.sales, public.stock, public.audit_log to authenticated;
grant insert on public.profiles to authenticated;
grant insert, delete on public.sales to authenticated;
grant insert, update, delete on public.stock to authenticated;

do $
begin
  begin
    alter publication supabase_realtime add table public.sales;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.stock;
  exception when duplicate_object then null;
  end;
end $;
